
bindAddr = "0.0.0.0"
bindPort = 7000
vhostHTTPPort = 8080
webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "{{cookiecutter.dashboard_user}}"
webServer.password = "{{cookiecutter.dashboard_password}}"

auth.method = "token"
auth.token = "{{cookiecutter.frps_token}}"

log.to = "/var/log/frps/frps.log"
# trace, debug, info, warn, error
log.level = "info"
log.maxDays = 3
# disable log colors when log.to is console, default is false
log.disablePrintColor = false

enablePrometheus = true