[http.middlewares.simpleAuth.basicAuth]
  users = [
	"{{cookiecutter.dashboard_password_hash}}"
  ]

[http.routers.api]
  rule = "Host(`{{cookiecutter.domain_traefik}}`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
{% if cookiecutter.dashboard_use_le == True %}
    certResolver = "lets-encrypt"
{% endif %}
